name: Run Linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm
      - name: Install eslint
        run: npm -g add eslint
      - name: Run ESLint
        run: eslint ./
